baseURL = "https://kiranmurali93.github.io/blog"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Kiran PK"
publishDir = "docs"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

[params]
title = "I'm Kiran PK"
author = "Kiran PK"
description = ""
profilePicture = "images/kiran.jpeg"
keywords = ""
# favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kiran-p-k/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/kiranmurali93"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://github.com/kiranmurali93"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:kiranmurali93@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
  
  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  